language: r
sudo: required
warnings_are_errors: false
dist: trusty
addons:
  apt:
    packages:
    - build-essential
    - jags
    - libxml2-dev
install:
  - R -e "install.packages(c('devtools', 'dplyr', 'vegan', 'onewaytests', 'ggplot2', 'DT'))"
  - R -e "devtools::install_github('rasmusab/bayesian_first_aid')"
  - R -e "devtools::install_github('rstudio/rmarkdown')"
  - R -e "rmarkdown::render('index.Rmd')"
env:
  global:
  -  secure: YItEMKAOG7379zT5cwe3VZ8SS9IcH+gsg7HaH//oJBa24dfEs8GxEAKDOIC5luwTuSZcKK9fgQLsniRCTZK4FRDVRzEmxWk3IpMHqe8RZdMUydzK5WObAexpI5yZnIpsAjkB96b+w+mYW4sauJ4I3BSf5AXxYZaBUTt7SHgaOk9555GeS228x49pnhuOnnetNVBAES6Oo7yu1qC5YQxSrTtUoppuHjf3fwM+jIoXXSyu8gD/7p8JQ5tsHsJMyitcILaPovlLMyyKvm3CQpyO76Sxv+/aRBwpdGf2Dp5HUjoYl07F3YNBI7vFJw6nvxc+R74C0MU7L6WW6zpD00CwWfRcoJdSC/WDDPmX1aYmaCJ3Sxei5XIpl6Cug1zqTkEOIQ/+naxsw2/ksR2ezcJq+7qznXcY6d1avsTAXFVp59ojvDoyvxxL5b4ezOngmHlerW54G5xiITc3RMT34Q7gzwMqggFcN0R/g8kfQ8OnVHZqQBNJOIL0HbQXktNwVwzPFG+aAsdox/RcWxIKx+ZejYzaVLshJNZi0VOz3i0jlyLXT6c+8qkQTMmsGhMwY8sMkee23IYEXd97HbbQPKxHLS1UQlxPLMwsSEWTPmadpJBcLpDsBSkDMDRpxMoxXfZma7pxFuaeb6DoR/Q4uqODDVq8gQReNiM/h5vsX9SXVsk=
