language: r
sudo: required
warnings_are_errors: false
dist: trusty
install:
  - R -e "install.packages('devtools', 'BayesianFirstAid', 'onewaytests', 'ggplot2')"
  - R -e "devtools::install_github('rstudio/rmarkdown')"
os:
- linux
after_success:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE"
  != "cron" ]] ; then R --no-save <<< "rmarkdown::render('index.Rmd')"; git checkout
  master; export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"; git
  config --global user.name "Travis CI"; git config --global user.email "$COMMIT_AUTHOR_EMAIL";
  git config credential.helper "store --file=.git/credentials"; echo "https://${GH_TOKEN}:@github.com"
  >> .git/credentials; git config push.default matching; git add --force index.html;
  git rm -r --cached $(find . -type d -name "*_cache"); git commit index.html -m "update
  auto-rendering to html [ci]" -m "$TRAVIS_COMMIT_MSG" || true; git push; fi;
env:
  global:
  -  secure: YItEMKAOG7379zT5cwe3VZ8SS9IcH+gsg7HaH//oJBa24dfEs8GxEAKDOIC5luwTuSZcKK9fgQLsniRCTZK4FRDVRzEmxWk3IpMHqe8RZdMUydzK5WObAexpI5yZnIpsAjkB96b+w+mYW4sauJ4I3BSf5AXxYZaBUTt7SHgaOk9555GeS228x49pnhuOnnetNVBAES6Oo7yu1qC5YQxSrTtUoppuHjf3fwM+jIoXXSyu8gD/7p8JQ5tsHsJMyitcILaPovlLMyyKvm3CQpyO76Sxv+/aRBwpdGf2Dp5HUjoYl07F3YNBI7vFJw6nvxc+R74C0MU7L6WW6zpD00CwWfRcoJdSC/WDDPmX1aYmaCJ3Sxei5XIpl6Cug1zqTkEOIQ/+naxsw2/ksR2ezcJq+7qznXcY6d1avsTAXFVp59ojvDoyvxxL5b4ezOngmHlerW54G5xiITc3RMT34Q7gzwMqggFcN0R/g8kfQ8OnVHZqQBNJOIL0HbQXktNwVwzPFG+aAsdox/RcWxIKx+ZejYzaVLshJNZi0VOz3i0jlyLXT6c+8qkQTMmsGhMwY8sMkee23IYEXd97HbbQPKxHLS1UQlxPLMwsSEWTPmadpJBcLpDsBSkDMDRpxMoxXfZma7pxFuaeb6DoR/Q4uqODDVq8gQReNiM/h5vsX9SXVsk=
